In [1]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import MinMaxScaler
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,Flatten,Dropout
from tensorflow.python.client import device_lib 

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [2]:
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 915980159168148595
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 2914163097
locality {
  bus_id: 1
  links {
  }
}
incarnation: 17967304649239538864
physical_device_desc: "device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1"
]


In [3]:
iris = load_iris()
print(iris.DESCR)
X = iris.data
y=iris.target
y = to_categorical(y)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.66,random_state=42)

In [5]:
scale = MinMaxScaler()

In [6]:
Scale_X_train = scale.fit_transform(X_train)
Scale_X_test = scale.fit_transform(X_test)

In [7]:
model = keras.Sequential([
    keras.layers.Dense(200,input_shape = (4,),activation='relu'),
    keras.layers.Dense(100,input_shape = (4,),activation='relu'),
    keras.layers.Dense(50,input_shape = (4,),activation='relu'),
    keras.layers.Dense(25,input_shape = (4,),activation='relu'),
    keras.layers.Dense(12,input_shape = (4,),activation='relu'),
    keras.layers.Dense(6,input_shape = (4,),activation='relu'),
    keras.layers.Dense(3,activation='sigmoid')
])
#log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
#tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)
#callbacks=[tensorboard_callback]
model.compile(optimizer='adam',
              loss = 'categorical_crossentropy'
              ,metrics = ['accuracy'])
model.fit(Scale_X_train,y_train,epochs = 150)

Epoch 1/150
4/4 [==============================] - 2s 7ms/step - loss: 1.0891 - accuracy: 0.3613
Epoch 2/150
4/4 [==============================] - 0s 7ms/step - loss: 1.0762 - accuracy: 0.3467
Epoch 3/150
4/4 [==============================] - 0s 7ms/step - loss: 1.0597 - accuracy: 0.3920
Epoch 4/150
4/4 [==============================] - 0s 7ms/step - loss: 1.0508 - accuracy: 0.4517
Epoch 5/150
4/4 [==============================] - 0s 7ms/step - loss: 1.0350 - accuracy: 0.5823
Epoch 6/150
4/4 [==============================] - 0s 7ms/step - loss: 1.0547 - accuracy: 0.6128
Epoch 7/150
4/4 [==============================] - 0s 7ms/step - loss: 1.0301 - accuracy: 0.6419
Epoch 8/150
4/4 [==============================] - 0s 6ms/step - loss: 1.0209 - accuracy: 0.5970
Epoch 9/150
4/4 [==============================] - 0s 7ms/step - loss: 1.0012 - accuracy: 0.6172
Epoch 10/150
4/4 [==============================] - 0s 6ms/step - loss: 1.0090 - accuracy: 0.6388
Epoch 11/150
4/4 [===========

In [16]:
prediction=model.predict(Scale_X_test)
length=len(prediction)
y_label=np.argmax(y_test,axis=1)
predict_label=np.argmax(prediction,axis=1)
accuracy=np.sum(y_label==predict_label)/length * 100 
print("Accuracy of the dataset",accuracy )

Accuracy of the dataset 98.0392156862745


In [19]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [20]:
print(confusion_matrix(y_label,predict_label))

[[19  0  0]
 [ 0 15  1]
 [ 0  0 16]]


In [22]:
print(classification_report(y_label,predict_label))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.94      0.97        16
           2       0.94      1.00      0.97        16

    accuracy                           0.98        51
   macro avg       0.98      0.98      0.98        51
weighted avg       0.98      0.98      0.98        51



In [23]:
print(accuracy_score(y_label,predict_label))

0.9803921568627451


In [24]:
model.save('mfl.h5')

In [27]:
from keras.models import load_model
new_model = load_model('mfl.h5')
new_model.predict_classes(Scale_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2, 1], dtype=int64)