In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('smsspamcollection.tsv',sep='\t')
df.head()

label                                            message  length  punct
0   ham  Go until jurong point, crazy.. Available only ...     111      9
1   ham                      Ok lar... Joking wif u oni...      29      6
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
3   ham  U dun say so early hor... U c already then say...      49      6
4   ham  Nah I don't think he goes to usf, he lives aro...      61      2

In [3]:
df.isnull().sum()

label      0
message    0
length     0
punct      0
dtype: int64

In [4]:
len(df)

5572

In [5]:
df['label'].value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [7]:
X = df.drop(['label','message'],axis = 1)
y = df['label']
train_X,test_X,train_y,test_y = train_test_split(X,y,train_size=0.8,random_state=5)

In [8]:
reg = LogisticRegression()
reg.fit(train_X,train_y)
y_pred = reg.predict(test_X)
print(confusion_matrix(test_y,y_pred))
print(classification_report(test_y,y_pred))

[[947  23]
 [142   3]]
              precision    recall  f1-score   support

         ham       0.87      0.98      0.92       970
        spam       0.12      0.02      0.04       145

    accuracy                           0.85      1115
   macro avg       0.49      0.50      0.48      1115
weighted avg       0.77      0.85      0.80      1115



In [9]:
df1 = pd.DataFrame(confusion_matrix(test_y,y_pred), index=['ham','spam'],columns=['ham','spam'])
df1

ham  spam
ham   947    23
spam  142     3

In [10]:
from  sklearn.naive_bayes import MultinomialNB
reg1 = nb_model = MultinomialNB()
reg1.fit(train_X,train_y)
y_pred = reg1.predict(test_X)
print(confusion_matrix(test_y,y_pred))
print(classification_report(test_y,y_pred))

[[968   2]
 [145   0]]
              precision    recall  f1-score   support

         ham       0.87      1.00      0.93       970
        spam       0.00      0.00      0.00       145

    accuracy                           0.87      1115
   macro avg       0.43      0.50      0.46      1115
weighted avg       0.76      0.87      0.81      1115



In [11]:
from  sklearn.svm import SVC
reg2  = MultinomialNB()
reg2.fit(train_X,train_y)
y_pred = reg2.predict(test_X)
print(confusion_matrix(test_y,y_pred))
print(classification_report(test_y,y_pred))

[[968   2]
 [145   0]]
              precision    recall  f1-score   support

         ham       0.87      1.00      0.93       970
        spam       0.00      0.00      0.00       145

    accuracy                           0.87      1115
   macro avg       0.43      0.50      0.46      1115
weighted avg       0.76      0.87      0.81      1115

