In [1]:
import numpy as np

In [25]:
var1 = 10

var2 = 200

result = var1 > var2

result

False

In [9]:
print(A,'\n\n\n',B)

[[1 2 3]
 [3 4 5]
 [5 4 6]] 


 [[5 7 3]
 [2 0 9]
 [2 5 8]]


In [10]:
print(A*B)

[[ 5 14  9]
 [ 6  0 45]
 [10 20 48]]


In [11]:
np.transpose(A)

array([[1, 3, 5],
       [2, 4, 4],
       [3, 5, 6]])

In [12]:
np.dot(A,B)

array([[15, 22, 45],
       [33, 46, 85],
       [45, 65, 99]])

In [15]:
np.cross(A,B)

array([[-15,  12,  -3],
       [ 36, -17,  -8],
       [  2, -28,  17]])

In [16]:
A + B

array([[ 6,  9,  6],
       [ 5,  4, 14],
       [ 7,  9, 14]])

In [17]:
A-B

array([[-4, -5,  0],
       [ 1,  4, -4],
       [ 3, -1, -2]])

In [18]:
2*A+3*B

array([[17, 25, 15],
       [12,  8, 37],
       [16, 23, 36]])

In [20]:
A.reshape(9,1)

array([[1],
       [2],
       [3],
       [3],
       [4],
       [5],
       [5],
       [4],
       [6]])

In [21]:
B.reshape(1,9)

array([[5, 7, 3, 2, 0, 9, 2, 5, 8]])

In [22]:
A@B

array([[15, 22, 45],
       [33, 46, 85],
       [45, 65, 99]])

In [24]:
A.reshape(1,9).T@B.reshape(9,1).T

array([[ 5,  7,  3,  2,  0,  9,  2,  5,  8],
       [10, 14,  6,  4,  0, 18,  4, 10, 16],
       [15, 21,  9,  6,  0, 27,  6, 15, 24],
       [15, 21,  9,  6,  0, 27,  6, 15, 24],
       [20, 28, 12,  8,  0, 36,  8, 20, 32],
       [25, 35, 15, 10,  0, 45, 10, 25, 40],
       [25, 35, 15, 10,  0, 45, 10, 25, 40],
       [20, 28, 12,  8,  0, 36,  8, 20, 32],
       [30, 42, 18, 12,  0, 54, 12, 30, 48]])